### PR TITLE
IBX-6578: FieldTypeRichText : autoloading issue

### PR DESCRIPTION
**Pull request by vidarl**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-6578](https://jira.ez.no/browse/IBX-6578)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 2.3
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Fixed stupid non-PSR4 compliance mistake

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Review by adamwojs — APPROVED** [review]

**Review by konradoboza — APPROVED** [review]

**Comment by adamwojs** [comment]
@vidarl Could you please merge up changes ?

**Comment by vidarl** [comment]
@adamwojs : Merging of https://github.com/ibexa/fieldtype-richtext/pull/135 completed

**Comment by konradoboza** [comment]
@vidarl merging up to `main` still needs to be done.

**Comment by vidarl** [comment]
Right, forgot about that. Merged to main  too now, 86bd7a6b9b03fbb206b02b414a81fb033fcd5f32

**Pull request merged**
