### PR TITLE
EZP-31405: fix embed image link removal

### PR DESCRIPTION
**Pull request by dew326**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31405](https://jira.ez.no/browse/EZP-31405)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 2.0
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This is merge up to 3.0 from the https://github.com/ezsystems/ezplatform-admin-ui/pull/1255 

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by mnocon** [comment]
@dew326 if it's a merge up to 3.0 shoudn't the basebranch here be 2.0?

**Comment by dew326** [comment]
@mnocon good catch, thanks.

**Comment by lserwatka** [comment]
Could you merge it up?

**Comment by dew326** [comment]
Done

**Pull request merged**
