### PR TITLE
EZP-29301: Added support for custom attributes on elements

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29301](https://jira.ez.no/browse/EZP-29301)
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | master
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Allows storing custom attributes. This PR does not provide any UI to modify/edit them in Online Editor. But it lets you migrate content from eZ Legacy to eZ Platform.

We used the following example content for tests:
```
<?xml version="1.0" encoding="UTF-8"?>\n
<section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink"
         xmlns:ezxhtml="http://ez.no/xmlns/ezpublish/docbook/xhtml"
         xmlns:ezcustom="http://ez.no/xmlns/ezpublish/docbook/custom" version="5.0-variant ezpublish-1.0">
    <title ezxhtml:level="2" ezxhtml:class="header_class_1">
        <ez-custom-attributes>
            <ezvalue key="ezca_header_1">header</ezvalue>
        </ez-custom-attributes>
        Header
    </title>
    <informaltable class="table_class_1" width="100%" title="summary">
        <ez-custom-attributes>
            <ezvalue key="summary">summary</ezvalue>
            <ezvalue key="caption"/>
            <ezvalue key="ezca_table_1">table</ezvalue>
        </ez-custom-attributes>
        <tbody>
            <tr class="tr_class_1">
                <ez-custom-attributes>
                    <ezvalue key="ezca_tr_1">tr1</ezvalue>
                </ez-custom-attributes>
                <td class="td_class_1" ezxhtml:width="0" valign="top">
                    <ez-custom-attributes>
                        <ezvalue key="valign">top</ezvalue>
                        <ezvalue key="ezca_td_1">td11</ezvalue>
                    </ez-custom-attributes>
                    <para>c11</para>
                </td>
                <td>
                    <para>c12</para>
                </td>
            </tr>
            <tr>
                <ez-custom-attributes>
                    <ezvalue key="ezca_tr_1">tr2</ezvalue>
                </ez-custom-attributes>
                <td>
                    <para>c21</para>
                </td>
                <td>
                    <para>c22</para>
                </td>
            </tr>
        </tbody>
    </informaltable>
    <para>
        <emphasis role="strong" ezxhtml:class="strong_class_1">
            <ez-custom-attributes>
                <ezvalue key="ezca_strong_1">strong</ezvalue>
            </ez-custom-attributes>
            Strong text
        </emphasis>
    </para>
    <para>
        <emphasis ezxhtml:class="em_class_1">
            <ez-custom-attributes>
                <ezvalue key="ezca_em_1">em</ezvalue>
            </ez-custom-attributes>
            Italic text
        </emphasis>
    </para>
    <para ezxhtml:class="para_class_1">
        <ez-custom-attributes>
            <ezvalue key="ezca_para_1">para_1</ezvalue>
            <ezvalue key="ezca_para_2">para_2</ezvalue>
        </ez-custom-attributes>
        Paragraph
    </para>
    <orderedlist ezxhtml:class="ol_class_1">
        <ez-custom-attributes>
            <ezvalue key="ezca_ol_1">ol</ezvalue>
        </ez-custom-attributes>
        <listitem ezxhtml:class="li_class_1">
            <ez-custom-attributes>
                <ezvalue key="ezca_li_1">li</ezvalue>
            </ez-custom-attributes>
            <para>Ordered item 1</para>
        </listitem>
        <listitem>
            <para>Ordered item 2</para>
        </listitem>
    </orderedlist>
    <itemizedlist ezxhtml:class="ul_class_1">
        <ez-custom-attributes>
            <ezvalue key="ezca_ul_1">ul</ezvalue>
        </ez-custom-attributes>
        <listitem>
            <para>Unordered item 1</para>
        </listitem>
        <listitem>
            <para>Unordered item 2</para>
        </listitem>
    </itemizedlist>
    <para>
        <link xlink:href="ezurl://67" xlink:show="none" ezxhtml:class="link_class_1">
            <ez-custom-attributes>
                <ezvalue key="ezca_link_1">link</ezvalue>
            </ez-custom-attributes>
            Link
        </link>
    </para>
</section>
```

Generated content in Online Editor:
```
<div class="ez-data-source__richtext">
    <h2 class="header_class_1" data-ez-custom-attirbute-ezca_header_1="header">Header</h2>
    <table class="table_class_1" title="summary" style="width:100%;" data-ez-custom-attirbute-summary="summary"
           data-ez-custom-attirbute-caption="" data-ez-custom-attirbute-ezca_table_1="table">
        <tbody>
            <tr class="tr_class_1" data-ez-custom-attirbute-ezca_tr_1="tr1">
                <td class="td_class_1" style="width:0px;vertical-align:top;" data-ez-custom-attirbute-valign="top"
                    data-ez-custom-attirbute-ezca_td_1="td11">
                    <p>c11</p>
                </td>
                <td>
                    <p>c12</p>
                </td>
            </tr>
            <tr data-ez-custom-attirbute-ezca_tr_1="tr2">
                <td>
                    <p>c21</p>
                </td>
                <td>
                    <p>c22</p>
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <strong class="strong_class_1" data-ez-custom-attirbute-ezca_strong_1="strong">Strong text</strong>
    </p>
    <p>
        <em class="em_class_1" data-ez-custom-attirbute-ezca_em_1="em">Italic text</em>
    </p>
    <p class="para_class_1" data-ez-custom-attirbute-ezca_para_1="para_1" data-ez-custom-attirbute-ezca_para_2="para_2">
        Paragraph
    </p>
    <ol class="ol_class_1" data-ez-custom-attirbute-ezca_ol_1="ol">
        <li class="li_class_1">Ordered item 1</li>
        <li>Ordered item 2</li>
    </ol>
    <ul class="ul_class_1" data-ez-custom-attirbute-ezca_ul_1="ul">
        <li>Unordered item 1</li>
        <li>Unordered item 2</li>
    </ul>
    <p>
        <a data-cke-saved-href="#" href="#" class="link_class_1" data-ez-custom-attirbute-ezca_link_1="link">Link</a>
    </p>
</div>
```

Output:
```
<div class="ezrichtext-field">
    <h2 class="header_class_1" data-ez-custom-attirbute-ezca_header_1="header">Header</h2>
    <table class="table_class_1" title="summary" style="width:100%;" data-ez-custom-attirbute-summary="summary"
           data-ez-custom-attirbute-caption="" data-ez-custom-attirbute-ezca_table_1="table">
        <tbody>
            <tr class="tr_class_1" data-ez-custom-attirbute-ezca_tr_1="tr1">
                <td class="td_class_1" style="width:0px;vertical-align:top;" data-ez-custom-attirbute-valign="top"
                    data-ez-custom-attirbute-ezca_td_1="td11">
                    <p>c11</p>
                </td>
                <td>
                    <p>c12</p>
                </td>
            </tr>
            <tr data-ez-custom-attirbute-ezca_tr_1="tr2">
                <td>
                    <p>c21</p>
                </td>
                <td>
                    <p>c22</p>
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <strong class="strong_class_1" data-ez-custom-attirbute-ezca_strong_1="strong">Strong text</strong>
    </p>
    <p>
        <em class="em_class_1" data-ez-custom-attirbute-ezca_em_1="em">Italic text</em>
    </p>
    <p class="para_class_1" data-ez-custom-attirbute-ezca_para_1="para_1" data-ez-custom-attirbute-ezca_para_2="para_2">
        Paragraph
    </p>
    <ol class="ol_class_1" data-ez-custom-attirbute-ezca_ol_1="ol">
        <li class="li_class_1">Ordered item 1</li>
        <li>Ordered item 2</li>
    </ol>
    <ul class="ul_class_1" data-ez-custom-attirbute-ezca_ul_1="ul">
        <li>Unordered item 1</li>
        <li>Unordered item 2</li>
    </ul>
    <p data-ez-custom-attirbute-ezca_link_1="link">Link</p>
</div>
```

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

// Maintainer edit: updated PR title and issue type - this is not a bug, it just was not supported yet in the new stack

### CODE REVIEW

**Comment by SerheyDolgushev** [comment]
@alongosz will do it a bit later today

**Comment by SerheyDolgushev** [comment]
@alongosz please have a look at https://github.com/ezsystems/ezplatform-richtext/pull/35/commits/10c38f51ccdc6e838f831d1928808586e16a4702

**Comment by SylvainGuittard** [comment]
ping @alongosz for another review :)

**Comment by SerheyDolgushev** [comment]
@alongosz done. Please review.

**Pull request merged**
