### PR TITLE
IBX-2814: Returned null instead of empty array when there are no child nodes

### PR DESCRIPTION
**Pull request by ViniTou**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2814
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | latest stable for bug fixes, master for new features
| **BC breaks**      | **yes**
| **Tests pass**     | yes
| **Doc needed**     | yes (this should probably be mentioned somewhere)

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Review by lserwatka — APPROVED** [review]

**Comment by dew326** [comment]
Shouldn't we change checks in our custom tags twig templates? I know this is not a case in this version because AlloyEditor works differently than CKEditor but I think we should have twigs prepared for null.

**Review by adamwojs — APPROVED** [review]

**Review by konradoboza — APPROVED** [review]
Hence this PR is targetting `ezplatform-richtext` I assume version 3.3 is also affected - worth mentioning in the ticket.

**Comment by ViniTou** [comment]
@dew326 
It works fine with current state of templates, as it simply adds empty html attribute. 

@konradoboza @micszo 
This issue is not reproducible on 3.3 as, Darek mentioned, AlloyEditor skips empty keys. But since it is technically possible to replace AE with CKEditor, and overall that solution helps us avoiding strange situations generally, I fixed it at 3.3.
So at 3.3, all you need to check if that it didnt broke anything.

**Review by micszo — APPROVED** [review]
Retested on Ibexa DXP v3.3 & v4.

**Pull request merged**
