### PR TITLE
README.md: Update link to Resources

### PR DESCRIPTION
**Pull request by adriendupuis**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | N/A
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | latest stable for bug fixes, master for new features
| **BC breaks**      | no
| **Tests pass**     | yes (nothing to test)
| **Doc needed**     | yes (doc update/fix)

Update link to Docbook schemas dir and Resources dir (where can be found DTD and other schemas)

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

### CODE REVIEW

**Comment by adamwojs** [comment]
PR target branch is incorrect. Could you please change it to latest stable branch ?

**Comment by adriendupuis** [comment]
> PR target branch is incorrect. Could you please change it to latest stable branch ?

@adamwojs OK. I'll rebase on 2.3

**Comment by adriendupuis** [comment]
> > PR target branch is incorrect. Could you please change it to latest stable branch ?
> 
> @adamwojs OK. I'll rebase on 2.3

@adamwojs I rebased on 2.3

**Review by adamwojs — APPROVED** [review]

**Review by Steveb-p — APPROVED** [review]

**Review by ciastektk — APPROVED** [review]

**Review by Nattfarinn — APPROVED** [review]

**Comment by adamwojs** [comment]
Could you please merge up changes @adriendupuis (or let me know if you don't have permissions)?

**Comment by lserwatka** [comment]
@adamwojs we need to merge it up.

**Comment by adamwojs** [comment]
Done.

**Pull request merged**
